/**
 * Banco de perguntas do diagnóstico LLMOps
 * Estrutura modular baseada nas macro-etapas
 */

export const ETAPAS = [
  { id: 'descoberta', nome: 'Descoberta & Alinhamento', ordem: 1 },
  { id: 'dados', nome: 'Dados & Contexto', ordem: 2 },
  { id: 'arquitetura', nome: 'Arquitetura & Desenho', ordem: 3 },
  { id: 'implementacao', nome: 'Implementação', ordem: 4 },
  { id: 'avaliacao', nome: 'Avaliação & Testes', ordem: 5 },
  { id: 'deploy', nome: 'Deploy & Observabilidade', ordem: 6 },
  { id: 'governanca', nome: 'Governança & Melhoria Contínua', ordem: 7 },
];

export const PERGUNTAS = {
  descoberta: {
    titulo: 'Descoberta & Alinhamento Estratégico',
    descricao: 'Entenda o contexto do negócio e os objetivos estratégicos',
    publico: 'Líderes de negócio, Product Managers e Arquitetos',
    objetivo: 'Mapear objetivos, stakeholders e critérios de sucesso',
    perguntas: [
      {
        id: 'problema_principal',
        tipo: 'textarea',
        pergunta: 'Descreva o principal problema ou oportunidade que deseja resolver com LLMs',
        placeholder: 'Ex: Automatizar atendimento ao cliente, gerar insights de documentos...',
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'objetivo_negocio',
        tipo: 'radio',
        pergunta: 'Qual o principal objetivo de negócio?',
        opcoes: [
          { valor: 'reduzir_custos', label: 'Reduzir custos operacionais', peso: 1 },
          { valor: 'aumentar_receita', label: 'Aumentar receita/vendas', peso: 1 },
          { valor: 'melhorar_experiencia', label: 'Melhorar experiência do cliente', peso: 1 },
          { valor: 'inovacao', label: 'Inovação/diferenciação de mercado', peso: 1 },
          { valor: 'produtividade', label: 'Aumentar produtividade interna', peso: 1 },
        ],
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'stakeholders',
        tipo: 'checkbox',
        pergunta: 'Quais stakeholders estão envolvidos?',
        opcoes: [
          { valor: 'executivos', label: 'Executivos/C-Level' },
          { valor: 'produto', label: 'Product/Gestão de Produto' },
          { valor: 'engenharia', label: 'Engenharia/Desenvolvimento' },
          { valor: 'dados', label: 'Data Science/ML' },
          { valor: 'compliance', label: 'Jurídico/Compliance' },
          { valor: 'usuarios', label: 'Usuários finais' },
        ],
        obrigatoria: true,
        peso: 1,
      },
      {
        id: 'maturidade_ia',
        tipo: 'escala',
        pergunta: 'Qual o nível de maturidade em IA/ML da organização?',
        min: 1,
        max: 10,
        labels: { 1: 'Iniciante', 5: 'Intermediário', 10: 'Avançado' },
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'prazo',
        tipo: 'radio',
        pergunta: 'Qual o prazo esperado para MVP/primeira versão?',
        opcoes: [
          { valor: '1-3_meses', label: '1-3 meses', peso: 1 },
          { valor: '3-6_meses', label: '3-6 meses', peso: 0.8 },
          { valor: '6-12_meses', label: '6-12 meses', peso: 0.6 },
          { valor: 'mais_12_meses', label: 'Mais de 12 meses', peso: 0.4 },
        ],
        obrigatoria: true,
        peso: 1,
      },
    ],
  },

  dados: {
    titulo: 'Dados & Contexto',
    descricao: 'Avalie a disponibilidade e qualidade dos dados',
    publico: 'Engenheiros de dados, Data Scientists e Arquitetos',
    objetivo: 'Mapear fontes de dados, qualidade e necessidades de processamento',
    perguntas: [
      {
        id: 'tem_dados',
        tipo: 'radio',
        pergunta: 'Você possui dados proprietários/específicos do domínio?',
        opcoes: [
          { valor: 'sim_estruturados', label: 'Sim, estruturados e organizados', peso: 1 },
          { valor: 'sim_nao_estruturados', label: 'Sim, mas não estruturados', peso: 0.7 },
          { valor: 'parcialmente', label: 'Parcialmente', peso: 0.5 },
          { valor: 'nao', label: 'Não tenho dados', peso: 0.2 },
        ],
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'volume_dados',
        tipo: 'radio',
        pergunta: 'Qual o volume de dados disponível?',
        opcoes: [
          { valor: 'pequeno', label: 'Pequeno (< 1GB)', peso: 0.5 },
          { valor: 'medio', label: 'Médio (1-100GB)', peso: 0.7 },
          { valor: 'grande', label: 'Grande (100GB - 1TB)', peso: 0.9 },
          { valor: 'muito_grande', label: 'Muito grande (> 1TB)', peso: 1 },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
      {
        id: 'tipo_dados',
        tipo: 'checkbox',
        pergunta: 'Quais tipos de dados você possui?',
        opcoes: [
          { valor: 'texto', label: 'Textos/Documentos' },
          { valor: 'tabular', label: 'Dados tabulares/estruturados' },
          { valor: 'codigo', label: 'Código-fonte' },
          { valor: 'imagens', label: 'Imagens' },
          { valor: 'audio', label: 'Áudio' },
          { valor: 'logs', label: 'Logs de sistema' },
        ],
        obrigatoria: true,
        peso: 1,
      },
      {
        id: 'qualidade_dados',
        tipo: 'escala',
        pergunta: 'Como avalia a qualidade/confiabilidade dos dados?',
        min: 1,
        max: 10,
        labels: { 1: 'Muito ruim', 5: 'Razoável', 10: 'Excelente' },
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'atualizacao_dados',
        tipo: 'radio',
        pergunta: 'Com que frequência os dados são atualizados?',
        opcoes: [
          { valor: 'tempo_real', label: 'Tempo real', peso: 1 },
          { valor: 'diaria', label: 'Diária', peso: 0.9 },
          { valor: 'semanal', label: 'Semanal', peso: 0.7 },
          { valor: 'mensal', label: 'Mensal ou menos', peso: 0.5 },
          { valor: 'estaticos', label: 'Dados estáticos', peso: 0.3 },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
    ],
  },

  arquitetura: {
    titulo: 'Arquitetura & Desenho Técnico',
    descricao: 'Defina padrões arquiteturais e requisitos técnicos',
    publico: 'Arquitetos, ML Engineers e Tech Leads',
    objetivo: 'Escolher a arquitetura adequada e definir componentes',
    perguntas: [
      {
        id: 'necessidade_contexto',
        tipo: 'radio',
        pergunta: 'O modelo precisa de contexto específico/atual para gerar respostas?',
        opcoes: [
          { valor: 'sim_critico', label: 'Sim, é crítico', peso: 1 },
          { valor: 'sim_desejavel', label: 'Sim, é desejável', peso: 0.7 },
          { valor: 'nao_necessario', label: 'Não é necessário', peso: 0.3 },
        ],
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'domain_specific',
        tipo: 'radio',
        pergunta: 'O domínio é altamente especializado (ex: médico, jurídico, científico)?',
        opcoes: [
          { valor: 'sim', label: 'Sim', peso: 1 },
          { valor: 'parcialmente', label: 'Parcialmente', peso: 0.6 },
          { valor: 'nao', label: 'Não', peso: 0.2 },
        ],
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'latencia',
        tipo: 'radio',
        pergunta: 'Qual o requisito de latência?',
        opcoes: [
          { valor: 'tempo_real', label: 'Tempo real (< 500ms)', peso: 1 },
          { valor: 'interativo', label: 'Interativo (< 3s)', peso: 0.8 },
          { valor: 'batch', label: 'Batch/assíncrono (> 1min)', peso: 0.4 },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
      {
        id: 'complexidade_tasks',
        tipo: 'checkbox',
        pergunta: 'Quais tipos de tarefas o sistema precisa realizar?',
        opcoes: [
          { valor: 'qa', label: 'Perguntas e respostas' },
          { valor: 'geracao', label: 'Geração de conteúdo' },
          { valor: 'resumo', label: 'Resumo/síntese' },
          { valor: 'extracao', label: 'Extração de informações' },
          { valor: 'classificacao', label: 'Classificação' },
          { valor: 'multimodal', label: 'Processamento multimodal' },
          { valor: 'agentes', label: 'Múltiplas tarefas encadeadas' },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
      {
        id: 'escalabilidade',
        tipo: 'radio',
        pergunta: 'Quantos usuários/requisições simultâneas são esperados?',
        opcoes: [
          { valor: 'baixa', label: 'Baixa (< 100/dia)', peso: 0.3 },
          { valor: 'media', label: 'Média (100-1000/dia)', peso: 0.6 },
          { valor: 'alta', label: 'Alta (> 1000/dia)', peso: 1 },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
    ],
  },

  implementacao: {
    titulo: 'Implementação & Desenvolvimento',
    descricao: 'Planeje a execução técnica e recursos necessários',
    publico: 'Desenvolvedores, ML Engineers e DevOps',
    objetivo: 'Avaliar capacidade técnica e planejar implementação',
    perguntas: [
      {
        id: 'time_tecnico',
        tipo: 'escala',
        pergunta: 'Qual o tamanho e experiência do time técnico?',
        min: 1,
        max: 10,
        labels: { 1: 'Pequeno/Junior', 5: 'Médio/Misto', 10: 'Grande/Sênior' },
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'preferencia_llm',
        tipo: 'radio',
        pergunta: 'Preferência de modelo LLM?',
        opcoes: [
          { valor: 'api_comercial', label: 'APIs comerciais (OpenAI, Anthropic)', peso: 0.8 },
          { valor: 'open_source', label: 'Open-source (Llama, Mistral)', peso: 0.6 },
          { valor: 'hibrido', label: 'Híbrido', peso: 0.9 },
          { valor: 'nao_sei', label: 'Não sei ainda', peso: 0.5 },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
      {
        id: 'infra_existente',
        tipo: 'checkbox',
        pergunta: 'Qual infraestrutura já está disponível?',
        opcoes: [
          { valor: 'cloud', label: 'Cloud (AWS, GCP, Azure)' },
          { valor: 'kubernetes', label: 'Kubernetes/Containers' },
          { valor: 'gpu', label: 'GPUs disponíveis' },
          { valor: 'ci_cd', label: 'CI/CD configurado' },
          { valor: 'monitoramento', label: 'Monitoramento/Observabilidade' },
          { valor: 'nada', label: 'Infraestrutura inicial' },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
      {
        id: 'orcamento',
        tipo: 'radio',
        pergunta: 'Qual o orçamento estimado mensal para APIs/infraestrutura?',
        opcoes: [
          { valor: 'baixo', label: 'Baixo (< $500/mês)', peso: 0.4 },
          { valor: 'medio', label: 'Médio ($500-5000/mês)', peso: 0.7 },
          { valor: 'alto', label: 'Alto (> $5000/mês)', peso: 1 },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
    ],
  },

  avaliacao: {
    titulo: 'Avaliação & Testes',
    descricao: 'Defina métricas e processos de validação',
    publico: 'QA, ML Engineers e Product Managers',
    objetivo: 'Estabelecer critérios de qualidade e testes',
    perguntas: [
      {
        id: 'metricas_sucesso',
        tipo: 'checkbox',
        pergunta: 'Quais métricas são mais importantes?',
        opcoes: [
          { valor: 'precisao', label: 'Precisão/Acurácia das respostas' },
          { valor: 'latencia', label: 'Latência/Tempo de resposta' },
          { valor: 'custo', label: 'Custo por requisição' },
          { valor: 'satisfacao', label: 'Satisfação do usuário' },
          { valor: 'relevancia', label: 'Relevância do conteúdo' },
        ],
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'golden_dataset',
        tipo: 'radio',
        pergunta: 'Possui dataset de teste/validação (golden dataset)?',
        opcoes: [
          { valor: 'sim_completo', label: 'Sim, completo e validado', peso: 1 },
          { valor: 'sim_parcial', label: 'Sim, parcial', peso: 0.6 },
          { valor: 'nao', label: 'Não possui', peso: 0.2 },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
      {
        id: 'processo_avaliacao',
        tipo: 'radio',
        pergunta: 'Como pretende avaliar a qualidade das respostas?',
        opcoes: [
          { valor: 'automatizada', label: 'Avaliação automatizada (métricas)', peso: 0.8 },
          { valor: 'humana', label: 'Avaliação humana especializada', peso: 0.6 },
          { valor: 'hibrida', label: 'Híbrida (automática + humana)', peso: 1 },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
    ],
  },

  deploy: {
    titulo: 'Deploy & Observabilidade',
    descricao: 'Planeje implantação e monitoramento',
    publico: 'DevOps, SRE e Engenheiros de Plataforma',
    objetivo: 'Garantir deploy seguro e monitoramento contínuo',
    perguntas: [
      {
        id: 'estrategia_deploy',
        tipo: 'radio',
        pergunta: 'Qual a estratégia de deploy preferida?',
        opcoes: [
          { valor: 'gradual', label: 'Gradual/Canary', peso: 1 },
          { valor: 'blue_green', label: 'Blue-Green', peso: 0.9 },
          { valor: 'big_bang', label: 'Deploy direto', peso: 0.5 },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
      {
        id: 'monitoramento',
        tipo: 'checkbox',
        pergunta: 'Quais aspectos deseja monitorar?',
        opcoes: [
          { valor: 'performance', label: 'Performance/Latência' },
          { valor: 'custo', label: 'Custos de API/Infra' },
          { valor: 'qualidade', label: 'Qualidade das respostas' },
          { valor: 'uso', label: 'Uso/Engajamento' },
          { valor: 'erros', label: 'Erros/Exceções' },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
      {
        id: 'rollback',
        tipo: 'radio',
        pergunta: 'Possui processo de rollback automatizado?',
        opcoes: [
          { valor: 'sim', label: 'Sim', peso: 1 },
          { valor: 'parcial', label: 'Parcialmente', peso: 0.6 },
          { valor: 'nao', label: 'Não', peso: 0.3 },
        ],
        obrigatoria: true,
        peso: 1,
      },
    ],
  },

  governanca: {
    titulo: 'Governança & Melhoria Contínua',
    descricao: 'Estabeleça processos de governança e evolução',
    publico: 'Compliance, Product Managers e Liderança',
    objetivo: 'Garantir conformidade, ética e melhoria contínua',
    perguntas: [
      {
        id: 'requisitos_regulatorios',
        tipo: 'checkbox',
        pergunta: 'Quais requisitos regulatórios se aplicam?',
        opcoes: [
          { valor: 'lgpd', label: 'LGPD/GDPR (Privacidade)' },
          { valor: 'sox', label: 'SOX/Auditoria financeira' },
          { valor: 'hipaa', label: 'HIPAA (Saúde)' },
          { valor: 'pci', label: 'PCI-DSS (Pagamentos)' },
          { valor: 'nenhum', label: 'Nenhum específico' },
        ],
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'bias_fairness',
        tipo: 'escala',
        pergunta: 'Qual a importância de monitorar viés e fairness?',
        min: 1,
        max: 10,
        labels: { 1: 'Baixa', 5: 'Média', 10: 'Crítica' },
        obrigatoria: true,
        peso: 2,
      },
      {
        id: 'processo_melhoria',
        tipo: 'radio',
        pergunta: 'Possui processo de feedback e melhoria contínua?',
        opcoes: [
          { valor: 'sim_estruturado', label: 'Sim, estruturado', peso: 1 },
          { valor: 'sim_informal', label: 'Sim, informal', peso: 0.6 },
          { valor: 'nao', label: 'Não possui', peso: 0.2 },
        ],
        obrigatoria: true,
        peso: 1.5,
      },
    ],
  },
};

